# Azure Pipeline YAML script for Python application using self-hosted agent
trigger:
  branches:
    include:
      - main

pool:
  name: test  # Specify the self-hosted agent pool name
  demands: 
    - agent.name -equals test  # Ensure the agent name matches 'test'

steps:
  # Step 1: Install Python manually
  - script: |
      node -v

  # # Step 2: Install dependencies
  # - script: |
  #     python3 -m pip install --upgrade pip
  #     pip3 install -r requirements.txt
  #   displayName: 'Install Python dependencies'

  # # Step 3: Navigate to the "AI Mouse" directory and run the Python app
  # - script: |
  #     cd "AI Mouse"
  #     python3 main.py
  #   displayName: 'Run Python application'
