# Azure Pipeline YAML script for Python application using self-hosted agent
trigger:
  branches:
    include:
      - main

pool:
  name: test  # Specify the self-hosted agent pool name
  demands: 
    - agent.name -equals test  # Ensure the agent name matches 'test'
# Azure DevOps Pipeline YAML for running PowerShell on Linux

steps:
- script: |
    echo "Running PowerShell script on Linux agent..."
    # Ensure pwsh is in the PATH, or provide the full path to your pwsh executable
    # If pwsh is not directly in PATH, you might need to specify the full path, e.g., /usr/local/bin/pwsh
   # pwsh -File $(System.DefaultWorkingDirectory)/your-script.ps1 -YourParameter "someValue"
  displayName: 'Run PowerShell Script'
 
# - task: PowerShell@2 # You can also use the PowerShell task, but ensure it uses pwsh
#   inputs:
#     targetType: 'filePath'
#     filePath: '$(System.DefaultWorkingDirectory)/your-script.ps1'
#     arguments: '-YourParameter "anotherValue"' # Pass parameters if your script accepts them
#     pwsh: true # This explicitly tells the task to use pwsh (PowerShell Core)
#   displayName: 'Run PowerShell Script using PowerShell@2 task'
 
# Example of an inline PowerShell script
- script: |
    pwsh -Command "./app_details.ps1"
 
# You would typically have your PowerShell script in your repository, e.g., 'your-script.ps1'
# Example content for your-script.ps1:
#
# param(
#     [string]$YourParameter
# )
#
# Write-Host "Hello from your-script.ps1!"
# Write-Host "Received prameter: $YourParameter"
# Get-ChildItem -Path /tmp | Write-Host
 
