# Azure Pipeline YAML script for Python application using self-hosted agent
trigger:
  branches:
    include:
      - main

pool:
  name: test  # Specify the self-hosted agent pool name
  demands: 
    - agent.name -equals test  # Ensure the agent name matches 'test'
# Azure DevOps Pipeline YAML for running PowerShell on Linux

steps:
- script: |
    echo "running script"
  displayName: 'running script'
# Example of an inline PowerShell script
- script: |
    pwsh -Command "./app_details.ps1"
  displayName: 'actual script'
 
# You would typically have your PowerShell script in your repository, e.g., 'your-script.ps1'
# Example content for your-script.ps1:
#
# param(
#     [string]$YourParameter
# )
#
# Write-Host "Hello from your-script.ps1!"
# Write-Host "Received prameter: $YourParameter"
# Get-ChildItem -Path /tmp | Write-Host
 
